name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf notion-bot
          git clone ${{ github.server_url }}/${{ github.repository }}
          cd notion-bot
          
          touch .env
          echo '\nNOTION_KEY="${{ secrets.NOTION_KEY }}"' >> .env
          echo '\nNOTION_DATABASE_ID="${{ secrets.NOTION_DATABASE_ID }}"' >> .env
          echo '\nTELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}"' >> .env
          
          docker compose up --no-deps --build -d
